logging:
    level:
        blog: WARN
        org: WARN
        org.hibernate.SQL: 'off'
mail:
    host: localhost
    mobilele: '"mobilele@example.com"'
    password: ${MAIL_PASSWORD:softuni}
    port: 1025
    username: ${MAIL_USERNAME:softuni}
mobilele:
    default:
        admin:
            pass: ${DEFAULT_ADMIN_PASS:topsecret}
    remember:
        me:
            key: ${REMEBER_ME_KEY:topsecret}
spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: ${MYSQL_PASSWORD}
        url: jdbc:mysql://localhost:3306/mobilele_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
        username: ${MYSQL_USER}
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
                format_sql: true
    mvc:
        hiddenmethod:
            filter:
                enabled: true


